spring:
    # DataSource Config
    datasource:
      url: jdbc:mysql://localhost:3306/tree
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    #session 失效时间
    session:
      timeout: 86400
